apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicle
  namespace: v2x
spec:
  selector:
    matchLabels:
      run: vehicle
  replicas: {NUM_VEHICLES}
  template:
    metadata:
      labels:
        app: v2x
        run: vehicle
    spec:
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        workerNode: "yes"
      containers:
      - name: tc
        image: selfrevocation/e2e-sim-tc:{VERSION}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80 
        envFrom:
          - configMapRef:
              name: system
        volumeMounts:
        - mountPath: /logs
          name: nfs
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "64Mi"
            cpu: "50m"
      - name: obu
        image: selfrevocation/e2e-sim-obu:{VERSION}
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8000
            protocol: UDP
          - containerPort: 9000
            protocol: UDP
        envFrom:
          - configMapRef:
              name: system
        env:
        - name: VEHICLE_MALICIOUS
          value: "0"
        - name: ATTACKER_LEVEL
          value: honest
        volumeMounts:
        - mountPath: /logs
          name: nfs
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "75m"
      volumes:
      - name: nfs
        hostPath:
          path: {LOG_DIR}