apiVersion: apps/v1
kind: Deployment
metadata:
  name: ra
  namespace: v2x
spec:
  selector:
    matchLabels:
      run: ra
  replicas: 1
  template:
    metadata:
      labels:
        app: v2x
        run: ra
    spec:
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        workerNode: "yes"
      containers:
      - name: ra
        image: selfrevocation/e2e-sim-ra:{VERSION}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80 
        envFrom:
          - configMapRef:
              name: system
        volumeMounts:
        - name: key
          mountPath: "/etc/credentials"
          readOnly: true
        - mountPath: /logs
          name: nfs
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
      volumes:
      - name: key
        secret:
          secretName: ra-keys
          optional: false
          items:
          - key: private
            path: ra_private.pem
      - name: nfs
        hostPath:
          path: {LOG_DIR}
---
apiVersion: v1
kind: Service
metadata: 
  name: ra
  namespace: v2x
spec:
  ports: 
    - name: http
      port: 80 
      targetPort: 80 
      protocol: TCP
  selector:
    run: ra
