services:
  issuer:
    image: selfrevocation/e2e-sim-issuer:${VERSION}
    build: src/issuer
    expose:
      - 80
    volumes:
      - "./cred/ra_public.pem:/etc/credentials/ra_public.pem"
      - "./logs:/logs"
    environment:
      - HOSTNAME=issuer
    env_file:
      - .env
  ra:
    image: selfrevocation/e2e-sim-ra:${VERSION}
    build: src/ra
    expose:
      - 80
    volumes:
      - "./cred/ra_private.pem:/etc/credentials/ra_private.pem"
      - "./logs:/logs"
    environment:
      - HOSTNAME=ra
    env_file:
      - .env
  rsu:
    image: selfrevocation/e2e-sim-rsu:${VERSION}
    build: src/rsu
    volumes:
      - "./logs:/logs"
    environment:
      - HOSTNAME=rsu
    env_file:
      - .env
    depends_on:
      - issuer
      - ra
  obu-1:
    image: selfrevocation/e2e-sim-obu:${VERSION}
    build: src/vehicle/obu
    volumes:
      - "./logs:/logs"
    env_file:
      - .env
    environment:
      - HOSTNAME=vehicle-1
      - TC_HOST=tc-1
      - VEHICLE_MALICIOUS=0
      - ATTACKER_LEVEL=honest
    depends_on:
      - issuer
      - ra
      - tc-1
  obu-2:
    image: selfrevocation/e2e-sim-obu:${VERSION}
    build: src/vehicle/obu
    volumes:
      - "./logs:/logs"
    environment:
      - HOSTNAME=vehicle-2
      - TC_HOST=tc-2
      - VEHICLE_MALICIOUS=1
    env_file:
      - .env
    depends_on:
      - issuer
      - ra
      - tc-2
  tc-1:
    image: selfrevocation/e2e-sim-tc:${VERSION}
    build: src/vehicle/tc
    volumes:
      - "./logs:/logs"
    environment:
      - HOSTNAME=vehicle-1
    env_file:
      - .env
    depends_on:
      - issuer
      - ra
  tc-2:
    image: selfrevocation/e2e-sim-tc:${VERSION}
    build: src/vehicle/tc
    volumes:
      - "./logs:/logs"
    environment:
      - HOSTNAME=vehicle-2
    env_file:
      - .env
    depends_on:
      - issuer
      - ra
  reporter:
    image: selfrevocation/e2e-sim-reporter:${VERSION}
    build: src/reporter
    volumes:
      - "./logs:/logs"
    environment:
      - HOSTNAME=reporter
    env_file:
      - .env
  web:
    image: selfrevocation/e2e-sim-web:${VERSION}
    build: src/web
    volumes:
      - "./logs:/logs"
    environment:
      - HOSTNAME=web
    env_file:
      - .env
    ports:
      - "8080:80"
  admin:
    image: yauritux/busybox-curl
    command: sleep 360000