services:
  issuer:
    image: selfrevocation/e2e-sim-issuer:${VERSION}
    build: src/issuer
    expose:
      - "80:80"
    volumes:
      - "./cred/ra_public.pem:/etc/credentials/ra_public.pem"
      - "./logs:/logs"
    environment:
      - HOSTNAME=issuer
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_TO_FILE=${LOG_TO_FILE}
      - PSEUDONYM_SIZE=${PSEUDONYM_SIZE}
  ra:
    image: selfrevocation/e2e-sim-ra:${VERSION}
    build: src/ra
    expose:
      - "80:80"
    volumes:
      - "./cred/ra_private.pem:/etc/credentials/ra_private.pem"
      - "./logs:/logs"
    environment:
      - HOSTNAME=ra
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_TO_FILE=${LOG_TO_FILE}
      - USE_EPOCHS=${USE_EPOCHS}
      - HEARTBEAT_GENERATION_PERIOD=${HEARTBEAT_GENERATION_PERIOD}
      - TC_STORE_LAST_PRL=${TC_STORE_LAST_PRL}
      - T_R=${T_R}
      - T_V=${T_V}
      - T_E=${T_E}
      - E_TOL=${E_TOL}
  rsu:
    image: selfrevocation/e2e-sim-rsu:${VERSION}
    build: src/rsu
    volumes:
      - "./logs:/logs"
    environment:
      - HOSTNAME=rsu
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_TO_FILE=${LOG_TO_FILE}
      - HEARTBEAT_DISTRIBUTION_PERIOD=${HEARTBEAT_DISTRIBUTION_PERIOD}
      - RSU_DROP_RATE=${RSU_DROP_RATE}
      - RSU_DELAY_RATE=${RSU_DELAY_RATE}
      - T_V=${T_V}
    depends_on:
      - issuer
      - ra
  obu-1:
    image: selfrevocation/e2e-sim-obu:${VERSION}
    build: src/vehicle/obu
    volumes:
      - "./logs:/logs"
    environment:
      - HOSTNAME=vehicle-1
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_TO_FILE=${LOG_TO_FILE}
      - USE_EPOCHS=${USE_EPOCHS}
      - TC_HOST=tc-1
      - PSEUDONYM_REFRESH_PERIOD=${PSEUDONYM_REFRESH_PERIOD}
      - V2V_GENERATION_PERIOD=${V2V_GENERATION_PERIOD}
      - HEARTBEAT_DISTRIBUTION_PERIOD=${HEARTBEAT_DISTRIBUTION_PERIOD}
      - NUM_PSEUDONYMS=${NUM_PSEUDONYMS}
      - VEHICLE_MALICIOUS=0
      - T_V=${T_V}
      - T_R=${T_R}
      - T_E=${T_E}
      - E_TOL=${E_TOL}
      - JOIN_MAX_DELAY=${JOIN_MAX_DELAY}
      - NUM_GROUPS=${NUM_GROUPS}
      - BLIND_ATTACKER_DROP_RATE=${BLIND_ATTACKER_DROP_RATE}
      - BLIND_2_ATTACKER_DELAYED=${BLIND_2_ATTACKER_DELAYED}
    depends_on:
      - issuer
      - ra
      - tc-1
  obu-2:
    image: selfrevocation/e2e-sim-obu:${VERSION}
    build: src/vehicle/obu
    volumes:
      - "./logs:/logs"
    environment:
      - HOSTNAME=vehicle-2
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_TO_FILE=${LOG_TO_FILE}
      - USE_EPOCHS=${USE_EPOCHS}
      - TC_HOST=tc-2
      - PSEUDONYM_REFRESH_PERIOD=${PSEUDONYM_REFRESH_PERIOD}
      - V2V_GENERATION_PERIOD=${V2V_GENERATION_PERIOD}
      - HEARTBEAT_DISTRIBUTION_PERIOD=${HEARTBEAT_DISTRIBUTION_PERIOD}
      - NUM_PSEUDONYMS=${NUM_PSEUDONYMS}
      - ATTACKER_LEVEL=${ATTACKER_LEVEL}
      - VEHICLE_MALICIOUS=1
      - T_V=${T_V}
      - T_R=${T_R}
      - T_E=${T_E}
      - E_TOL=${E_TOL}
      - JOIN_MAX_DELAY=${JOIN_MAX_DELAY}
      - NUM_GROUPS=${NUM_GROUPS}
      - BLIND_ATTACKER_DROP_RATE=${BLIND_ATTACKER_DROP_RATE}
      - BLIND_2_ATTACKER_DELAYED=${BLIND_2_ATTACKER_DELAYED}
    depends_on:
      - issuer
      - ra
      - tc-2
  tc-1:
    image: selfrevocation/e2e-sim-tc:${VERSION}
    build: src/vehicle/tc
    volumes:
      - "./logs:/logs"
    environment:
      - HOSTNAME=vehicle-1
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_TO_FILE=${LOG_TO_FILE}
      - USE_EPOCHS=${USE_EPOCHS}
      - NUM_PSEUDONYMS=${NUM_PSEUDONYMS}
      - PSEUDONYM_SIZE=${PSEUDONYM_SIZE}
      - MIN_PSEUDONYM_LIFETIME=${MIN_PSEUDONYM_LIFETIME}
      - HARD_REVOCATION=${HARD_REVOCATION}
      - TC_STORE_LAST_PRL=${TC_STORE_LAST_PRL}
      - T_R=${T_R}
      - T_V=${T_V}
      - T_E=${T_E}
      - E_TOL=${E_TOL}
    depends_on:
      - issuer
      - ra
  tc-2:
    image: selfrevocation/e2e-sim-tc:${VERSION}
    build: src/vehicle/tc
    volumes:
      - "./logs:/logs"
    environment:
      - HOSTNAME=vehicle-2
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_TO_FILE=${LOG_TO_FILE}
      - USE_EPOCHS=${USE_EPOCHS}
      - NUM_PSEUDONYMS=${NUM_PSEUDONYMS}
      - PSEUDONYM_SIZE=${PSEUDONYM_SIZE}
      - MIN_PSEUDONYM_LIFETIME=${MIN_PSEUDONYM_LIFETIME}
      - HARD_REVOCATION=${HARD_REVOCATION}
      - TC_STORE_LAST_PRL=${TC_STORE_LAST_PRL}
      - T_R=${T_R}
      - T_V=${T_V}
      - T_E=${T_E}
      - E_TOL=${E_TOL}
    depends_on:
      - issuer
      - ra
  reporter:
    image: selfrevocation/e2e-sim-reporter:${VERSION}
    build: src/reporter
    volumes:
      - "./logs:/logs"
    environment:
      - HOSTNAME=reporter
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_TO_FILE=${LOG_TO_FILE}
      - USE_EPOCHS=${USE_EPOCHS}
      - REPORT_MALICIOUS_ONLY=${REPORT_MALICIOUS_ONLY}
      - REPORT_PERIOD=${REPORT_PERIOD}
      - REPLAY_RATE=${REPLAY_RATE}
      - NUM_GROUPS=${NUM_GROUPS}
      - T_V=${T_V}
      - T_E=${T_E}
      - E_TOL=${E_TOL}
  admin:
    image: yauritux/busybox-curl
    command: sleep 360000