name: artifacts
on:
  workflow_dispatch:

jobs:
  proofs:
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@master
    -
      name: Run main design (centralized-time)
      run: |
        cd proofs
        make prove VERSION=v1.6.1 MODEL=centralized-time THREADS=4 OUT_FILE=output_centralized.spthy
        docker logs -n 200 tamarin > out/log_centralized.txt
      timeout-minutes: 10
    -
      name: Run alternative design (distributed-time)
      run: |
        cd proofs
        make prove VERSION=v1.6.1 MODEL=distributed-time THREADS=4 OUT_FILE=output_distributed.spthy
        docker logs -n 200 tamarin > out/log_distributed.txt
      timeout-minutes: 10
    -
      name: Remove temp files
      run: |
        cd proofs
        rm -rf out/theory.spthy out/oracle.py
    - 
      name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: proofs
        path: proofs/out
  simulation:
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@master
    -
      name: Setup
      run: |
        cd simulation
        make run_minikube
        make build_minikube
    -
      name: Test run
      run: |
        cd simulation
        make run_simulations CONF=conf/ci.yaml SCENARIO=scenario-a1 RUN=1-honest SIM_TIME=120 DOWN_TIME=30
        make clean
    -
      name: Run simulations
      run: |
        cd simulation
        make run_simulations CONF=conf/ci.yaml
    -
      name: Generate plots
      run: |
        cd simulation
        make plot_all
    - 
      name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: simulation
        path: simulation/simulations
  prl:
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@master
    -
      name: Transition graph
      run: |
        cd prl
        make tikz
    -
      name: p-plot
      run: |
        cd prl
        make p-plot
    -
      name: n-plot
      run: |
        cd prl
        make n-plot
    -
      name: t-plot
      run: |
        cd prl
        make t-plot
    -
      name: tv-distribution
      run: |
        cd prl
        make tv-distribution
    - 
      name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: prl-plots
        path: prl/plots