name: test-running
on:
  push:
    branches:
      - master
      - main
  workflow_dispatch: # Allow manual triggering

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@master
    -
      name: Tamarin
      run: |
        cd proofs
        make test
        make clean
      timeout-minutes: 5
    -
      name: PRL
      run: |
        cd prl
        make test
        make tikz
        make clean

      timeout-minutes: 5
    -
      name: Simulation
      run: |
        cd simulation
        pip install -r scripts/requirements.txt
        make build
        make test SIM_TIME=60
        make clean
      timeout-minutes: 5