name: test-running
on:
  push:
    branches:
      - master
      - main
  workflow_dispatch: # Allow manual triggering

jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
    -
      uses: actions/checkout@master
    -
      name: Install dependencies
      run: |
        echo "" | ./install.sh -f
        echo "" | ./install.sh
      timeout-minutes: 5
    -
      name: Tamarin
      run: |
        cd proofs
        make test MODEL=centralized-time OUT_FILE=output_centralized.spthy
        make test MODEL=distributed-time OUT_FILE=output_distributed.spthy
        make clean
      timeout-minutes: 5
    -
      name: Simulation
      run: |
        cd simulation
        make run_minikube
        make build_minikube
        make run_simulations CONF=conf/ci.yaml SCENARIO=scenario-a1 RUN=1-honest SIM_TIME=120 DOWN_TIME=30
        make clean_all
      timeout-minutes: 10
    -
      name: PRL
      run: |
        cd prl
        make test
        make single
        make clean

      timeout-minutes: 5