name: run-simulations
on:
  workflow_dispatch:

jobs:
  Minikube:
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@master
    -
      name: Setup
      run: |
        cd simulation
        pip install -r scripts/requirements.txt
        make run_minikube
    -
      name: Test run scenario a1-honest
      run: |
        cd simulation
        make run_simulations SCENARIO=scenario-a1 RUN=1-honest SIM_TIME=300 DOWN_TIME=30