name: artifacts
on:
  workflow_dispatch:

jobs:
  simulation:
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@master
    -
      name: Setup
      run: |
        cd simulation
        make run_minikube
        make build_minikube
    -
      name: Test run
      run: |
        cd simulation
        make run_simulations SCENARIO=scenario-a1 RUN=1-honest SIM_TIME=120 DOWN_TIME=30
    -
      name: Run Scenario A1 (4 runs x 10 min)
      run: |
        cd simulation
        make run_simulations SCENARIO=scenario-a1 SIM_TIME=600 DOWN_TIME=60
    -
      name: Generate plots
      run: |
        cd simulation
        make plot SCENARIO=scenario-a1 PLOTS=honest,smart,blind,smart-prl
    - 
      name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: simulation
        path: simulation/simulations
  proofs:
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@master
    -
      name: Run main design (centralized-time)
      run: |
        cd proofs
        make prove VERSION=v1.6.1 MODEL=centralized-time THREADS=4 OUT_FILE=output_centralized.spthy
        while docker ps --filter name=tamarin | grep tamarin ; do sleep 1; done
        docker logs -n 200 tamarin > out/log_centralized.txt
      timeout-minutes: 10
    -
      name: Run alternative design (distributed-time)
      run: |
        cd proofs
        make prove VERSION=v1.6.1 MODEL=distributed-time THREADS=4 OUT_FILE=output_distributed.spthy
        while docker ps --filter name=tamarin | grep tamarin ; do sleep 1; done
        docker logs -n 200 tamarin > out/log_distributed.txt
      timeout-minutes: 10
    - 
      name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: proofs
        path: proofs/out